name: pylot
description: A app of planets that are in our solar system.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  http: ^0.12.0+4
  cached_network_image: ^2.0.0
  webview_flutter: ^0.3.19+9
  hydrated_bloc: ^3.0.0
  json_annotation: ^3.0.1
  cupertino_icons: ^0.1.2
  device_preview: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: any

flutter:
  uses-material-design: true
  fonts:
    - family: Oxanium
      fonts:
        - asset: fonts/Oxanium/Oxanium-Bold.ttf
        - asset: fonts/Oxanium/Oxanium-ExtraBold.ttf
        - asset: fonts/Oxanium/Oxanium-ExtraLight.ttf
        - asset: fonts/Oxanium/Oxanium-Light.ttf
        - asset: fonts/Oxanium/Oxanium-Medium.ttf
        - asset: fonts/Oxanium/Oxanium-Regular.ttf
        - asset: fonts/Oxanium/Oxanium-SemiBold.ttf